// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyLittleRPG_ElGuendouz.Data.Context;

#nullable disable

namespace MyLittleRPG_ElGuendouz.Migrations
{
    [DbContext(typeof(MonsterContext))]
    partial class MonsterContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MyLittleRPG_ElGuendouz.Models.Monster", b =>
                {
                    b.Property<int>("idMonster")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idMonster"));

                    b.Property<int>("defenseBase")
                        .HasColumnType("int");

                    b.Property<int>("experienceBase")
                        .HasColumnType("int");

                    b.Property<int>("forceBase")
                        .HasColumnType("int");

                    b.Property<string>("nom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("pointVieBase")
                        .HasColumnType("int");

                    b.Property<int>("pokemonId")
                        .HasColumnType("int");

                    b.Property<string>("spriteUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("type1")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("type2")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("idMonster");

                    b.ToTable("Monsters");
                });

            modelBuilder.Entity("MyLittleRPG_ElGuendouz.Models.Tuile", b =>
                {
                    b.Property<int>("PositionX")
                        .HasColumnType("int");

                    b.Property<int>("PositionY")
                        .HasColumnType("int");

                    b.Property<bool>("EstTraversable")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("PositionX", "PositionY");

                    b.ToTable("Tuiles");
                });
#pragma warning restore 612, 618
        }
    }
}
